Ejercicio: Adivinar numero aleatorio
ikerllorens/Fundamentos-de-Programacion pull request #24
Opened 2022-11-20 21:45 UTC by IrvingAlx

Programa que genera un numero aleatorio entre 1 y 1000 y permite al usuario adivinar que numero es, ademas de indicar el numero de intentos en el que lo logro.

2022-11-22 19:54 UTC, ikerllorens requested changes
Podemos eliminar el .exe del repo porfa? Si quieres añadelo al .gitignore para que ignore cualquier .exe

2022-11-22 19:55 UTC, ikerllorens commented
Fuera del .exe. Gran contribución Irving!

2022-11-22 20:13 UTC, IrvingAlx commented
Ya elimine directo el .exe

2022-11-22 23:16 UTC, ikerllorens approved these changes

2023-08-11 04:33 UTC, merged

2023-08-11 04:36 UTC, IrvingAlx commented
[like]  IRVING ALEJANDRO VEGA LAGUNAS reacted to your message:
________________________________
From: Íker Lloréns ***@***.***>
Sent: Friday, August 11, 2023 4:33:42 AM
To: ikerllorens/Fundamentos-de-Programacion ***@***.***>
Cc: IRVING ALEJANDRO VEGA LAGUNAS ***@***.***>; Author ***@***.***>
Subject: Re: [ikerllorens/Fundamentos-de-Programacion] Ejercicio: Adivinar numero aleatorio (PR #24)


Merged #24<https://github.com/ikerllorens/Fundamentos-de-Programacion/pull/24> into main.

—
Reply to this email directly, view it on GitHub<https://github.com/ikerllorens/Fundamentos-de-Programacion/pull/24#event-10065757400>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARY5MFHKGN2URWSB32MKHILXUWY2NANCNFSM6AAAAAASGBLYGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>